version: "3"
services:
  app:
    build:
      context: "."
      dockerfile: Dockerfile.production
    image: swimmwatch/devops-for-programmers-project-74
    command: bash -c "sleep 3 && npm test"
    depends_on:
      - db
    environment:
      - DATABASE_NAME
      - DATABASE_USERNAME
      - DATABASE_PASSWORD
      - DATABASE_PORT
      - DATABASE_HOST
  db:
    image: postgres:15.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD-password}
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local