version: "3"
services:
  app:
    build:
      context: "."
      dockerfile: Dockerfile.production
    image: swimmwatch/devops-for-programmers-project-74
    command: bash -c "sleep 3 && npm test"
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:15.1-alpine
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local