name: Build and deploy application

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    services:
      postgres:
        image: postgres:15.1-alpine
        env:
          POSTGRES_PASSWORD:  ${{ secrets.DATABASE_PASSWORD }}
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_DATABASE_HOST: "db"
          envkey_DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          envkey_DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          envkey_DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          envkey_POSTGRES_USER: ${{ secrets.DATABASE_USERNAME }}
          envkey_POSTGRES_DB: ${{ secrets.DATABASE_NAME }}
          envkey_POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          file_name: .env
      - name: Build images
        run: docker compose -f docker-compose.yml build
      - name: Run tests
        run: make ci
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: swimmwatch/devops-for-programmers-project-74

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: swimmwatch/devops-for-programmers-project-74:latest
          labels: ${{ steps.meta.outputs.labels }}